#!/bin/bash

# Script pour configurer le domaine personnalisé sur CloudFront
# ATTENTION: Ce script nécessite des actions manuelles dans la console AWS

DISTRIBUTION_ID="E1CDGKUKVPVX55"
DOMAIN="supratourstravel.com"
WWW_DOMAIN="www.supratourstravel.com"

echo "🔧 Configuration du domaine personnalisé pour CloudFront"
echo "==============================================="
echo ""
echo "Distribution ID: $DISTRIBUTION_ID"
echo "Domaine principal: $DOMAIN"
echo "Domaine www: $WWW_DOMAIN"
echo ""
echo "⚠️  ÉTAPES MANUELLES REQUISES :"
echo ""
echo "1. 📋 Aller dans la console AWS CloudFront:"
echo "   https://console.aws.amazon.com/cloudfront/v3/home"
echo ""
echo "2. 🎯 Sélectionner la distribution: $DISTRIBUTION_ID"
echo ""
echo "3. ✏️  Cliquer sur 'Edit' dans l'onglet 'General'"
echo ""
echo "4. 🌐 Dans 'Alternate domain names (CNAMEs)', ajouter:"
echo "   - $DOMAIN"
echo "   - $WWW_DOMAIN"
echo ""
echo "5. 🔒 Pour 'SSL Certificate':"
echo "   - Sélectionner 'Custom SSL certificate'"
echo "   - Cliquer 'Request certificate' (cela ouvrira ACM)"
echo "   - Demander un certificat pour: *.$DOMAIN"
echo "   - Valider le certificat via DNS ou email"
echo ""
echo "6. 💾 Sauvegarder les changements"
echo ""
echo "7. 🌍 Configurer le DNS chez votre hébergeur:"
echo "   Type  | Nom | Valeur"
echo "   ------|-----|-------"
echo "   CNAME | www | d3izgnl4i03wrb.cloudfront.net"
echo "   A     | @   | [IP de CloudFront ou utiliser ALIAS si supporté]"
echo ""
echo "⏰ Temps de propagation: 5-48 heures selon l'hébergeur DNS"
echo ""
echo "✅ Après configuration, votre site sera accessible via:"
echo "   - https://$DOMAIN"
echo "   - https://$WWW_DOMAIN"
echo ""
echo "🔍 Pour vérifier la propagation DNS:"
echo "   dig $DOMAIN"
echo "   dig $WWW_DOMAIN"